[profile.default]
src = "src"
solc_version = "0.8.26"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.0.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
